### ISSUE TITLE
has anyone tried to port to URP, or is it impossible?

### ISSUE THREAD

**Issue by vasco-dev** [GarrettGunnell/Post-Processing#2]

**Comment by GarrettGunnell** [comment]
Shader authoring for URP and HDRP is considerably different, especially for custom post processing effects since I don't even think those are possible in URP without a lot of jank.

**Comment by vasco-dev** [comment]
> Shader authoring for URP and HDRP is considerably different, especially for custom post processing effects since I don't even think those are possible in URP without a lot of jank.

yeah that is what I thought, thanks for the quick response :)
